#ifndef LAROC_UTIL_VISITORD_H
#define LAROC_UTIL_VISITORD_H

typedef enum VisitOrder {
  VISIT_ORD_DEFAULT,
  VISIT_ORD_REVERSE,
  VISIT_ORD_DEFAULT_UNTIL_UNCHANGED,
  VISIT_ORD_REVERSE_UNTIL_UNCHANGED,
} VisitOrder;

#endif
